[package]
name = "exex-avs-operator"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
resolver = "2"

[dependencies]
tokio.workspace = true
async-trait.workspace = true
web3 = "0.19.0"
serde_json.workspace = true
hex-literal = "0.4.1"
hex = "0.4.3"